diff --git a/Dockerfile b/Dockerfile
index 8594738..2c27338 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -40,6 +40,10 @@ ENV MERCURE_TRANSPORT_URL=bolt:///data/mercure.db
 ENV PHP_INI_SCAN_DIR=":$PHP_INI_DIR/app.conf.d"

 ###> recipes ###
+###> doctrine/doctrine-bundle ###
+RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*
+RUN install-php-extensions pdo_sqlite
+###< doctrine/doctrine-bundle ###
 ###< recipes ###

 COPY --link frankenphp/conf.d/10-app.ini $PHP_INI_DIR/app.conf.d/
